name: New issue triage
on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  issue_cleanup:
    name: Clean issue body
    uses: mui/mui-public/.github/workflows/issues_body-cleanup.yml@9741b9d5e30ddcd5bccf4020dd59ec56ea4932cb # master
    permissions:
      contents: read
      issues: write
